version: "3.8"
services:
  app:
    build: ./infra/php
    volumes:
      - ./${WORK_DIR}:/work
  web:
    image: nginx:1.18-alpine
    ports:
      - 80:80
    volumes:
      - ./${WORK_DIR}:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./storage/mysql:/var/lib/mysql:cached
      - ./infra/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=${TZ}
    tty: true

volumes:
  db-store: