version: "3.8"
services:
  app:
    build: ./infra/php
    volumes:
      - "./${WORK_DIR}:/work"
  web:
    image: nginx:1.18-alpine
    ports:
      - 80:80
    volumes:
      - ./${WORK_DIR}:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work